"""Traces the 2022-09-09 score-PSI step change to the graph lookback evicting day 1.

Supports the "the biggest drift signal in the monitor is generated by our own feature
pipeline" entry in reports/challenges.md's Phase 7 section, and the daily PSI series in
reports/results.md's Phase 7 section.

The Phase 7 daily score-PSI series is flat and stable for three days and then steps up
by ~4x on a single day, with no gradual ramp:

    2022-09-06  PSI 0.0707  stable
    2022-09-07  PSI 0.0685  stable
    2022-09-08  PSI 0.0783  stable
    2022-09-09  PSI 0.2845  significant   <-- step change
    2022-09-10  PSI 0.2856  significant

A step change is the interesting shape. Gradual drift is a population slowly moving;
a step means something switched. This script identifies what switched, and the answer is
uncomfortable: nothing in the data switched. `src/graph_features.build_daily_graph_features`
bounds each day's account graph to a trailing `lookback_days` (7) window, pruning edges
whose date is `< date - 7 days` (added in Phase 3 to stop the graph growing without
bound — see investigations/phase3_feature_engineering/02_...). The dataset starts
2022-09-01. Therefore:

    day 2022-09-08: cutoff 2022-09-01 -> nothing older than 09-01 exists, nothing pruned
    day 2022-09-09: cutoff 2022-09-02 -> 09-01's edges are evicted, for the first time

and 2022-09-01 is the single largest day in HI-Small (~1.11M of 5.08M transactions, 22%).
So on 09-09 every account's graph features are recomputed on a graph that just lost 22%
of the dataset's edges at once. The features step, the score distribution steps, and PSI
faithfully reports "significant drift" on a population that did not change.

The script checks three things:
1. the eviction date implied by the lookback arithmetic is exactly 09-09,
2. 09-01 really is the largest day (so the eviction is a large shock, not a small one),
3. the CSI between 09-08 and 09-09 is dominated by `*_graph_*` features, not by the
   window/velocity features or the raw amounts.

Run from the repo root (needs data/processed/features.parquet and models/):
    venve/python.exe investigations/phase7_monitoring/02_graph_lookback_eviction_step_change.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
import pandas as pd

from src.data_loader import load_config
from src.model import load_xgboost_model, prepare_feature_matrix, time_ordered_split
from src.monitoring import characteristic_stability, psi_table, quantile_bin_edges


def main() -> None:
    config = load_config()
    split_cfg = config["split"]
    mon_cfg = config["monitoring"]
    n_bins = mon_cfg["psi_bins"]
    epsilon = float(mon_cfg["psi_epsilon"])
    lookback_days = config["graph_features"]["lookback_days"]

    print("Loading modelling table ...")
    df = pd.read_parquet(config["paths"]["modelling_table"])

    # --- 1. When does the lookback first evict anything? -------------------------------
    first_day = df["timestamp"].min().normalize()
    day_counts = df.groupby(df["timestamp"].dt.normalize()).size()
    # graph_features prunes edges with date < (date - lookback); the first day on which
    # that removes the dataset's first day is first_day + lookback + 1 day.
    first_eviction = first_day + pd.Timedelta(days=lookback_days) + pd.Timedelta(days=1)

    print(f"\n=== 1. Lookback arithmetic (graph_features.lookback_days = {lookback_days}) ===")
    print(f"  dataset first day     : {first_day.date()}")
    print(f"  first eviction day    : {first_eviction.date()}")
    print(f"  observed PSI step day : 2022-09-09")
    assert first_eviction.date() == pd.Timestamp("2022-09-09").date(), first_eviction
    print("  -> the arithmetic lands exactly on the observed step. ")

    # --- 2. How big is the shock? ------------------------------------------------------
    print("\n=== 2. Size of the evicted day ===")
    print(day_counts.head(10).to_string())
    largest = day_counts.idxmax()
    print(
        f"\n  largest day: {largest.date()} with {day_counts.max():,} rows "
        f"({day_counts.max() / len(df):.1%} of the whole dataset)"
    )
    print(
        f"  the evicted day IS the largest day: {largest.normalize() == first_day}\n"
        "  -> the first eviction is also the largest possible eviction."
    )

    # --- 3. Which features carry the step? ---------------------------------------------
    train_df, val_df, test_df = time_ordered_split(
        df, split_cfg["train_frac"], split_cfg["val_frac"]
    )
    del df

    model = load_xgboost_model(config["paths"]["models_dir"])
    x_train, _ = prepare_feature_matrix(train_df)
    train_scores = model.predict_proba(x_train)[:, 1]

    x_val, _ = prepare_feature_matrix(val_df)
    x_test, _ = prepare_feature_matrix(test_df)
    later_x = pd.concat([x_val, x_test], ignore_index=True)
    later_scores = np.concatenate(
        [model.predict_proba(x_val)[:, 1], model.predict_proba(x_test)[:, 1]]
    )
    later_days = pd.concat(
        [val_df["timestamp"], test_df["timestamp"]], ignore_index=True
    ).dt.date

    before = (later_days == pd.Timestamp("2022-09-08").date()).to_numpy()
    after = (later_days == pd.Timestamp("2022-09-09").date()).to_numpy()

    print("\n=== 3. CSI across the step (09-08 -> 09-09), top 10 ===")
    csi = characteristic_stability(
        later_x[before].reset_index(drop=True),
        later_x[after].reset_index(drop=True),
        n_bins=n_bins,
        epsilon=epsilon,
        thresholds=mon_cfg["psi_thresholds"],
    )
    print(csi.head(10).to_string(index=False, float_format=lambda v: f"{v:.4f}"))

    top_10 = csi.head(10)["feature"]
    n_graph = int(top_10.str.contains("_graph_").sum())
    print(
        f"\n  {n_graph} of the top 10 CSI drivers across the step are `*_graph_*` "
        "features.\n  -> the step is the graph layer, not the velocity/amount layers."
    )

    # --- 4. How the step shows up in the score distribution ----------------------------
    print("\n=== 4. Where the score PSI comes from, either side of the step ===")
    edges = quantile_bin_edges(train_scores, n_bins)
    for label, mask in (("2022-09-08", before), ("2022-09-09", after)):
        table = psi_table(train_scores, later_scores[mask], n_bins, epsilon)
        bottom = table.iloc[0]
        print(
            f"  {label}: PSI {table['psi_contribution'].sum():.4f}  "
            f"| bottom decile holds {bottom['current_pct']:.2%} of the day "
            f"(train: {bottom['reference_pct']:.2%}), "
            f"contributing {bottom['psi_contribution']:.4f}"
        )
    print(
        "\n  The bottom score decile drains from ~4% to ~1% of the day's rows overnight.\n"
        "  Those are the low-history, low-graph-connectivity transactions; evicting the\n"
        "  largest day of edges is exactly what removes them."
    )

    print(
        "\nCONCLUSION: the largest sustained drift signal this monitor produces on\n"
        "HI-Small is an artifact of the model's own feature pipeline, not of the data.\n"
        "A production monitor would have paged someone to investigate a data incident\n"
        "that does not exist. See reports/challenges.md's Phase 7 section."
    )


if __name__ == "__main__":
    main()
