"""Assert the README's load-bearing numbers match the artifacts they claim to come from.

PLAN.md's Phase 11 check is "read the README fresh, top to bottom; every numeric claim
traces to results.md or the notebooks". Read by a human, that check passes right up until
the pipeline is rerun and the README quietly becomes wrong — and a stale headline number in
the most-read file in the repo is the single worst failure this project could ship, because
it is invisible and it is exactly what a reviewer will quote back.

So the headline figures are asserted against `app/data/demo_metrics.json`, which is
regenerated by `scripts/build_demo_artifact.py` from the real pipeline. If a rebuild moves
a number, this fails until the README is updated to match.

Deliberately scoped to the numbers a reader would act on — the headline, the operating
point, the AUCs, precision@k, per-typology recall, split sizes. Prose figures that are
stable properties of the dataset (row counts, ACH share) are not re-derived here; they're
covered by the loaders' own tests.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

README = Path("README.md")
METRICS = Path("app/data/demo_metrics.json")

pytestmark = pytest.mark.skipif(
    not (README.exists() and METRICS.exists()),
    reason="README or demo metrics missing",
)


@pytest.fixture(scope="module")
def readme() -> str:
    return README.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def readme_flat() -> str:
    """The README with every whitespace run collapsed to a single space.

    Needed for any claim that spans a line break — the source is hard-wrapped, so
    "between 67.6% and\n89.8%" contains no literal "67.6% and 89.8%" to match against.
    Asserting on the raw text instead makes these tests fail on reflowing a paragraph,
    which is noise rather than signal.
    """
    return re.sub(r"\s+", " ", README.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def metrics() -> dict:
    with open(METRICS, encoding="utf-8") as f:
        return json.load(f)


def test_headline_reduction_and_alert_counts(readme, metrics):
    h = metrics["headline"]

    assert f"{h['fp_reduction']:.1%}" in readme          # 96.6%
    assert f"{h['model_alerts']:,}" in readme            # 10,011
    assert f"{h['baseline_alerts']:,}" in readme         # 297,564
    assert f"{h['matched_recall']:.1%}" in readme        # 68.8%


def test_tail_excluded_headline_is_quoted(readme, metrics):
    assert f"{metrics['headline_excluding_tail']['fp_reduction']:.1%}" in readme  # 96.2%


def test_test_split_size_and_positive_count(readme, metrics):
    split = metrics["test_split"]

    assert f"{split['n_rows']:,}" in readme              # 1,015,669
    assert f"{split['n_positives']:,}" in readme         # 1,797


def test_auc_figures(readme, metrics):
    assert f"{metrics['auc']['pr_auc']:.4f}" in readme   # 0.3967
    assert f"{metrics['auc']['roc_auc']:.4f}" in readme  # 0.9828


def test_precision_at_k_figures(readme, metrics):
    for k in ("100", "500", "1000"):
        value = metrics["precision_at_k"][k]
        # 92% renders without a decimal; 74.8% and 60.6% with one.
        rendered = f"{value:.0%}" if (value * 100) % 1 == 0 else f"{value:.1%}"
        assert rendered in readme, f"precision@{k} ({rendered}) not found in README"


def test_every_typology_recall_matches(readme, metrics):
    for row in metrics["recall_per_typology"]:
        rendered = f"{row['recall']:.1%}"
        assert rendered in readme, f"{row['typology']} recall {rendered} not in README"


def test_typology_recall_range_claim(readme_flat, metrics):
    """The README claims all eight typologies land 'between 67.6% and 89.8%'. Assert those
    really are the min and max, so the claim can't survive a rebuild that breaks it.
    """
    recalls = [row["recall"] for row in metrics["recall_per_typology"]]

    assert f"{min(recalls):.1%} and {max(recalls):.1%}" in readme_flat


def test_scale_pos_weight_and_feature_count(readme, metrics):
    model = metrics["model"]

    assert f"{model['scale_pos_weight']:,.0f}" in readme   # 1,325
    assert str(model["n_features"]) in readme              # 54


def test_live_demo_link_is_present_and_near_the_top(readme):
    match = re.search(r"https://[a-z0-9-]+\.streamlit\.app/?", readme)

    assert match, "no Streamlit demo URL in README"
    # PLAN.md Phase 11: the live link must be prominent, not buried.
    assert match.start() < len(readme) * 0.1


def test_accuracy_is_not_claimed_as_a_metric(readme_flat):
    """CLAUDE.md's hard constraint: accuracy is not a headline metric at this prevalence.
    The README may explain why it's excluded, but must never report one.
    """
    for match in re.finditer(r"accuracy", readme_flat, flags=re.IGNORECASE):
        window = readme_flat[max(0, match.start() - 160) : match.start() + 160]
        if re.search(r"\d+(\.\d+)?%", window):
            # The only permitted case: the illustration that a do-nothing model scores
            # 99.82% accuracy, which is an argument against the metric, not a result.
            assert "never laundering" in window or "catching nothing" in window, (
                f"README appears to report an accuracy figure: {window!r}"
            )
